/**
 * Drizzle schema — Better Auth core tables (docs/13 §1) + news_items (docs/12 §4).
 * Better Auth field names follow its Drizzle adapter conventions exactly.
 */

import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
} from "drizzle-orm/pg-core";
import type { ArticleBlock } from "@/lib/article-blocks";

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (t) => [index("session_user_id_idx").on(t.userId)],
);

export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [index("account_user_id_idx").on(t.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [index("verification_identifier_idx").on(t.identifier)],
);

/**
 * Own articles (docs/28) — block content as jsonb, one row per piece.
 * type drives layout A–E; live blogs keep updates in articleUpdates.
 * autoGenerated=true rows (markets wraps) are labeled as such in the UI.
 */
export const articles = pgTable(
  "articles",
  {
    id: text("id").primaryKey(),
    slug: text("slug").notNull().unique(),
    type: text("type").notNull().default("standard"), // standard|live|wrap|feature|opinion
    vertical: text("vertical").notNull().default("markets"), // lib/verticals.ts slug
    title: text("title").notNull(),
    dek: text("dek"),
    byline: text("byline").notNull().default("Indrani News"),
    heroImageUrl: text("hero_image_url"),
    heroImageCredit: text("hero_image_credit"),
    blocks: jsonb("blocks").$type<ArticleBlock[]>().notNull().default([]),
    autoGenerated: boolean("auto_generated").notNull().default(false),
    demo: boolean("demo").notNull().default(false), // seeded demo content — banner in UI
    live: boolean("live").notNull().default(false), // live blog still open
    readMinutes: integer("read_minutes").notNull().default(1),
    publishedAt: timestamp("published_at").notNull(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (t) => [
    index("articles_vertical_idx").on(t.vertical, t.publishedAt),
    index("articles_type_idx").on(t.type, t.publishedAt),
  ],
);

/** Live blog updates (docs/28 layout B) — reverse-chron cards under one article. */
export const articleUpdates = pgTable(
  "article_updates",
  {
    id: text("id").primaryKey(),
    articleId: text("article_id")
      .notNull()
      .references(() => articles.id, { onDelete: "cascade" }),
    title: text("title"),
    body: text("body").notNull(),
    keyMoment: boolean("key_moment").notNull().default(false),
    postedAt: timestamp("posted_at").notNull().defaultNow(),
  },
  (t) => [index("article_updates_article_idx").on(t.articleId, t.postedAt)],
);

/** Ingested RSS items (docs/12 §4) — dedup by id (hash of url), queryable by category/lang. */
export const newsItems = pgTable(
  "news_items",
  {
    id: text("id").primaryKey(),
    title: text("title").notNull(),
    url: text("url").notNull(),
    source: text("source").notNull(),
    category: text("category").notNull().default("top"),
    lang: text("lang").notNull().default("en"),
    summary: text("summary"),
    imageUrl: text("image_url"),
    publishedAt: timestamp("published_at").notNull(),
    ingestedAt: timestamp("ingested_at").notNull().defaultNow(),
  },
  (t) => [
    index("news_items_category_idx").on(t.category, t.publishedAt),
    index("news_items_published_at_idx").on(t.publishedAt),
  ],
);
