/**
 * Article queries + Markets Wrap composition — server-side only (imports db).
 * Renderers receive plain rows; block model lives in lib/article-blocks.ts.
 */

import { and, desc, eq, ne } from "drizzle-orm";
import { db } from "@/lib/db";
import { articles, articleUpdates } from "@/lib/db/schema";
import type { ArticleType } from "@/lib/article-blocks";
import { readMinutes } from "@/lib/article-blocks";
import { getQuotes } from "@/lib/data/chain";
import { buildWrapContent, WRAP_SYMBOLS } from "@/lib/wrap-generator";

export type ArticleRow = typeof articles.$inferSelect;
export type ArticleUpdateRow = typeof articleUpdates.$inferSelect;

export async function getArticleBySlug(slug: string): Promise<ArticleRow | null> {
  const rows = await db.select().from(articles).where(eq(articles.slug, slug)).limit(1);
  return rows[0] ?? null;
}

export async function listArticles(opts: {
  vertical?: string;
  type?: ArticleType;
  excludeId?: string;
  limit?: number;
}): Promise<ArticleRow[]> {
  const { vertical, type, excludeId, limit = 6 } = opts;
  const conditions = [
    vertical ? eq(articles.vertical, vertical) : undefined,
    type ? eq(articles.type, type) : undefined,
    excludeId ? ne(articles.id, excludeId) : undefined,
  ].filter((c) => c !== undefined);
  return db
    .select()
    .from(articles)
    .where(conditions.length ? and(...conditions) : undefined)
    .orderBy(desc(articles.publishedAt))
    .limit(limit);
}

/** Live blog updates, newest first. `sincePostedAt` (ISO) filters for polling. */
export async function getArticleUpdates(
  articleId: string,
  sincePostedAt?: string,
): Promise<ArticleUpdateRow[]> {
  const rows = await db
    .select()
    .from(articleUpdates)
    .where(eq(articleUpdates.articleId, articleId))
    .orderBy(desc(articleUpdates.postedAt));
  if (!sincePostedAt) return rows;
  const since = new Date(sincePostedAt).getTime();
  return rows.filter((r) => r.postedAt.getTime() > since);
}

/** IST calendar date (YYYY-MM-DD) — wraps key on the Indian trading day. */
export function istDateKey(now = new Date()): string {
  return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata" }).format(now);
}

function wrapDateLabel(dateKey: string): string {
  return new Date(`${dateKey}T12:00:00Z`).toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

/**
 * Today's wrap: return the stored row, else generate from live quotes and
 * store (docs/28 layout C; answer 3 — real data, labeled auto-generated).
 * Returns null when the date isn't today and nothing is stored, or when no
 * market data is available to generate from.
 */
export async function getOrGenerateWrap(dateKey: string): Promise<ArticleRow | null> {
  const slug = `markets-wrap-${dateKey}`;
  const existing = await getArticleBySlug(slug);
  if (existing) return existing;
  if (dateKey !== istDateKey()) return null; // never fabricate a past session

  const quotesRes = await getQuotes(WRAP_SYMBOLS);
  if (!quotesRes.data) return null;
  const content = buildWrapContent(quotesRes.data, wrapDateLabel(dateKey));
  if (!content) return null;

  const now = new Date();
  const row: typeof articles.$inferInsert = {
    id: crypto.randomUUID(),
    slug,
    type: "wrap",
    vertical: "markets",
    title: content.title,
    dek: content.dek,
    byline: "Indrani Markets Automation",
    blocks: content.blocks,
    autoGenerated: true,
    readMinutes: readMinutes(content.blocks),
    publishedAt: now,
    updatedAt: now,
  };
  // Concurrent ISR renders may race — first insert wins, rest reread.
  await db.insert(articles).values(row).onConflictDoNothing({ target: articles.slug });
  return (await getArticleBySlug(slug)) ?? null;
}
