/**
 * Article header — docs/28 layouts A–E variants driven by article.type:
 * standard/wrap (kicker + title + dek + byline + share), feature (full-bleed
 * dark hero), opinion (author-forward + views disclosure), live (pulsing LIVE
 * badge). Demo and auto-generated rows get explicit banners (docs/18 §2).
 */

import Link from "next/link";
import type { ArticleRow } from "@/lib/articles";
import { VERTICALS } from "@/lib/verticals";
import { timeAgo } from "@/lib/format";
import ShareRow from "@/components/news/article/share-row";
import RemoteImage from "@/components/news/remote-image";

function Banners({ article }: { article: ArticleRow }) {
  return (
    <>
      {article.demo && (
        <p className="mb-4 rounded border border-dashed border-[var(--accent-down)] px-3 py-2 text-xs font-semibold uppercase tracking-wide text-[var(--accent-down)]">
          Demo content — sample article for layout preview, not a real news event
        </p>
      )}
      {article.autoGenerated && (
        <p className="mb-4 rounded border border-border bg-muted/40 px-3 py-2 text-xs text-muted-foreground">
          <span className="font-semibold uppercase tracking-wide">Auto-generated</span> — assembled
          by Indrani Markets Automation from live market data. Numbers are real; prose is templated.
        </p>
      )}
    </>
  );
}

function MetaAndShare({ article, path }: { article: ArticleRow; path: string }) {
  return (
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-y border-border py-3">
      <p className="text-sm text-muted-foreground">
        <span className="font-semibold text-foreground">{article.byline}</span>
        <span aria-hidden="true"> · </span>
        <time dateTime={article.updatedAt.toISOString()}>
          Updated {timeAgo(article.updatedAt.toISOString())}
        </time>
        <span aria-hidden="true"> · </span>
        {article.readMinutes} min read
      </p>
      <ShareRow path={path} title={article.title} />
    </div>
  );
}

export default function ArticleHeader({ article, path }: { article: ArticleRow; path: string }) {
  const vertical = VERTICALS.find((v) => v.slug === article.vertical);
  const kicker = (
    <Link
      href={`/${article.vertical}`}
      className="text-xs font-bold uppercase tracking-widest"
      style={{ color: vertical?.accent ?? "var(--accent-brand)" }}
    >
      {vertical?.name ?? article.vertical}
    </Link>
  );

  if (article.type === "feature") {
    return (
      <header className="mb-8">
        <div className="relative -mx-4 mb-6 flex min-h-[320px] items-end overflow-hidden bg-[#0c0e14] px-4 py-8 sm:rounded-lg md:min-h-[420px]">
          {article.heroImageUrl && <RemoteImage src={article.heroImageUrl} priority />}
          <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/40 to-black/10" />
          <div className="relative max-w-3xl text-white">
            <p className="text-xs font-bold uppercase tracking-widest text-[var(--accent-brand)]">
              The Big Take
            </p>
            <h1 className="mt-2 text-balance text-4xl font-bold leading-tight md:text-5xl">
              {article.title}
            </h1>
            {article.dek && <p className="mt-3 text-lg text-white/80">{article.dek}</p>}
          </div>
        </div>
        <Banners article={article} />
        {article.heroImageCredit && (
          <p className="text-xs uppercase text-muted-foreground">Credit: {article.heroImageCredit}</p>
        )}
        <MetaAndShare article={article} path={path} />
      </header>
    );
  }

  if (article.type === "opinion") {
    return (
      <header className="mb-8">
        <Banners article={article} />
        <p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Opinion</p>
        <p className="mt-2 text-xl font-bold" style={{ color: "var(--accent-brand)" }}>
          {article.byline}
          <span className="ml-2 align-middle text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
            Columnist
          </span>
        </p>
        <h1 className="mt-3 text-balance text-3xl font-bold leading-tight md:text-4xl">
          {article.title}
        </h1>
        {article.dek && <p className="mt-3 text-lg italic text-muted-foreground">{article.dek}</p>}
        <MetaAndShare article={article} path={path} />
        <p className="mt-3 text-xs text-muted-foreground">
          The views expressed are the author&rsquo;s own.
        </p>
      </header>
    );
  }

  return (
    <header className="mb-8">
      <Banners article={article} />
      <div className="flex items-center gap-3">
        {article.type === "live" && (
          <span className="inline-flex items-center gap-1.5 rounded bg-[var(--accent-down)] px-2 py-0.5 text-[11px] font-bold uppercase tracking-wider text-white">
            <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-white" aria-hidden="true" />
            Live
          </span>
        )}
        {kicker}
      </div>
      <h1 className="mt-2 text-balance text-3xl font-bold leading-tight md:text-4xl">
        {article.title}
      </h1>
      {article.dek && <p className="mt-3 text-lg text-muted-foreground">{article.dek}</p>}
      <MetaAndShare article={article} path={path} />
      {article.heroImageUrl && (
        <figure className="mt-6">
          <div className="relative aspect-video overflow-hidden rounded-lg">
            <RemoteImage src={article.heroImageUrl} priority />
          </div>
          {article.heroImageCredit && (
            <figcaption className="mt-2 text-xs uppercase text-muted-foreground">
              Credit: {article.heroImageCredit}
            </figcaption>
          )}
        </figure>
      )}
    </header>
  );
}
